#!/bin/bash
SVRegBinDir="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/
ScriptName=$(basename "${BASH_SOURCE[0]}")

if [ -z "$1" ]; then
  echo BrainSuite v21a SVReg run all
  echo for more information, please see: http://brainsuite.org
	echo
  echo "This script takes the outputs of the BrainSuite cortical surface "
  echo "extraction script and performs (1) cortical thickness estimation;"
  echo "(2) surface-constrained volumetric registration (svreg); (3) mapping"
  echo "of the subject cortical thickness to the atlas space; and (4) statistical "
  echo "analysis of various measures generated by the previous programs."
  echo
	echo "usage: $ScriptName input_image [ atlas_image ] [ flags ]"
  echo "  where input_image is the path and filename for the T1w base image "
  echo "  atlas_image is the path and filename for the labeled atlas (optional)."
  echo "  all flags will be pass to svreg."
  echo "" 
  echo "Possible flags for svreg include: "
  echo " -V#     Controls the verbosity of output messages (# is 0, 1, or 2)"
  echo " -s      Checks if all files necessary for volume registration are present;"
  echo "         if so, skip the surface registration and perform only volume registration"
  echo " -S      surface registration only"
  echo " -k      keep the intermediate files after the svreg sequence is complete"
  echo " -t      display timestamps along with output messages"
  echo " -U      single threaded mode"
  echo "For the full list, please check http://brainsuite.org/processing/svreg/usage/"
  echo ""
	exit 0;
fi;
echo "using SVReg in bin dir $SVRegBinDir"

set -e
"${SVRegBinDir}thicknessPVC.sh" "$1"
if [ $? -ne 0 ]; then echo "svreg_runall halted because thicknessPVC returned an error."; exit 1; fi;
"${SVRegBinDir}svreg.sh" "$@"
if [ $? -ne 0 ]; then echo "svreg_runall halted because svreg returned an error."; exit 1; fi;
"${SVRegBinDir}svreg_thickness2atlas.sh" "$1"
if [ $? -ne 0 ]; then echo "svreg_runall halted because svreg_thickness2atlas returned an error."; exit 1; fi;
"${SVRegBinDir}generate_stats_xls.sh" "$1"
if [ $? -ne 0 ]; then echo "svreg_runall halted because generate_stats_xls returned an error."; exit 1; fi;

