name: Build SVReg on GitHub Runner
run-name: Build SVReg by @${{ github.actor }}

on: [push]
env:
  VERSION: 26a_RC1
  BUILD_NO: 9999
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
jobs:
  build:
    permissions: write-all
    name: Build SVReg on GitHub Runner
    strategy:
      fail-fast: false
      matrix:
        # os: [ windows-latest, macos-13]
        os: [ubuntu-latest, windows-latest, macos-13, macos-15]
    runs-on:
      labels: ["${{ matrix.os }}" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            MATLAB_Compiler
            Image_Processing_Toolbox
            Medical_Imaging_Toolbox
            Parallel_Computing_Toolbox

      - name: set MacOS x64 environment variables
        if: runner.os == 'macOS' && runner.arch == 'X64'
        run: |
          echo "Package=${PWD}/compile_scripts/svreg_${{ env.VERSION }}_build${{ env.BUILD_NO }}_maci64.tar.gz" >> $GITHUB_ENV

      - name: set MacOS x64 environment variables
        if: runner.os == 'macOS' && runner.arch == 'ARM64'
        run: |
          echo "Package=${PWD}/compile_scripts/svreg_${{ env.VERSION }}_build${{ env.BUILD_NO }}_maca64.tar.gz" >> $GITHUB_ENV

      - name: set Linux environment variables
        if: runner.os == 'Linux'
        run: |
          echo "Package=${PWD}/compile_scripts/svreg_${{ env.VERSION }}_build${{ env.BUILD_NO }}_linux.tar.gz" >> $GITHUB_ENV

      - name: set Windows environment variables
        if: runner.os == 'Windows'
        run: |
          echo "Package=${PWD}/compile_scripts/svreg_${{ env.VERSION }}_build${{ env.BUILD_NO }}_win64.zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: setup MSVC compiler
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
  
      - name: build Windows air programs
        if: runner.os == 'Windows'
        working-directory: 3rdParty
        run: |
          cl.exe /Fe:AIR_bin\ warp_points.cpp lib\win64\RPW_x64_MT.lib
          cl.exe /Fe:AIR_bin\ warp_coord_vol.cpp lib\win64\RPW_x64_MT.lib
  
      - name: build Mac air programs
        if: runner.os == 'macOS' && runner.arch == 'X64'
        working-directory: 3rdParty
        run: |
          install -d AIR_bin
          g++ -Llib/maci64 warp_points.cpp -lRPW -lm -O3 -o AIR_bin/warp_points_mac
          g++ -Llib/maci64 warp_coord_vol.cpp -lRPW -lm -O3 -o AIR_bin/warp_coord_vol_mac
  
      - name: build Mac air programs
        if: runner.os == 'macOS' && runner.arch == 'ARM64'
        working-directory: 3rdParty
        run: |
          install -d AIR_bin
          g++ -Llib/maca64 warp_points.cpp -lRPW -lm -O3 -o AIR_bin/warp_points_mac -target arm64-apple-macos15
          g++ -Llib/maca64 warp_coord_vol.cpp -lRPW -lm -O3 -o AIR_bin/warp_coord_vol_mac -target arm64-apple-macos15
  
      - name: build Linux air programs
        if: runner.os == 'Linux'
        working-directory: 3rdParty
        run: |
          install -d AIR_bin
          g++ -Llib/linux warp_points.cpp -lRPW -lm -O3 -o AIR_bin/warp_points_linux
          g++ -Llib/linux warp_coord_vol.cpp -lRPW -lm -O3 -o AIR_bin/warp_coord_vol_linux
            
      - name: compile SVReg Mex files
        uses: matlab-actions/run-command@v2
        with:
          startup-options: -sd compile_scripts
          command: compile_mex
          
      - name: compile SVReg
        uses: matlab-actions/run-command@v2
        with:
          startup-options: -sd compile_scripts
          command: "compile_all --package ${{ env.VERSION }}${{ env.BUILD_NO }}"  

      - name: Publish ${{ env.Package }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.Package }}"
          tag: v${{ env.VERSION }}        
          allowUpdates: true
